spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:5432}/${PROD_DB_NAME:bbs_prod}
    username: ${PROD_DB_USER:postgres}
    password: ${PROD_DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

swagger:
  server-url: ${SWAGGER_SERVER_URL}
